### ISSUE TITLE
Merge Julia.tmbundle with Julia-sublime

### ISSUE THREAD

**Issue by ViktorQvarfordt** [JuliaEditorSupport/Julia.tmbundle#13]
I recently took over maintenance of [Julia-sublime](https://github.com/epitron/Julia-sublime), which is the standard Julia language support package for Sublime Text. I've since found Julia.tmbundle and realized it works as-is with Sublime Text 2/3.

What do you say about letting https://packagecontrol.io/packages/Julia point to this repo instead? I would be nice to not have duplicate code.

If this sounds like a good idea, I can include the improvements that have been made to `Julia.tmLanguage` from Julia-sublime into this repo.

Furthermore, it would be good to advertise this package as a sublime package as well (so that the sublime users can find it. Although, having it on Package Control mostly takes care of this).

Lastly, I see that this repo has not seen much development lately. If wanted, I could take care of some maintenance.

**Comment by ViktorQvarfordt** [comment]
If someone sees a reason not to merge the two packages, it would still be good if Julia-sublime resided in https://github.com/JuliaLang/.

**Comment by ViktorQvarfordt** [comment]
I see a reason to not completely merge the repos: We want to be able to set sublime settings in a `sublime-settings` file.

However, these two repos could perhaps share the synatx config file somehow. 

Furthermore, this repo should be moved to https://github.com/JuliaEditorSupport/. Given that JuliaLang is getting crowded, packages are being moved to more appropriate places, such as JuliaMath, JuliaWeb, etc. Editor support repos are being moved to JuliaEditorSupport.

**Comment by tkelman** [comment]
I moved the package and invited a couple of the past contributors to that organization.

**Comment by ViktorQvarfordt** [comment]
The [sublime package](https://github.com/JuliaEditorSupport/Julia-sublime) has evolved further, it uses the new `.sublime-syntax` format for even better syntax highlighting support and incorporates unicode completion in a superior way that is tailored for sublime.

Therefore, merging the two packages is no longer desired.
